# Generated by Django 3.1.6 on 2022-11-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='image_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.TextField(default=''),
        ),
    ]
